Repository swiftotter/den, pull requests merged in 2022-08, with the labels that each got.

#13 Allow switching of database distributions through .env file
  commands/env-init.cmd
  docs/environments/customizing.md
  docs/environments/magento2.md
  docs/environments/shopware.md
  environments/includes/db.base.yml
  environments/magento2/magento2.splitdb.checkout.base.yml
  environments/magento2/magento2.splitdb.sales.base.yml
Labels: enhancement

#27 Update project name to den in sign-certificate command
  commands/sign-certificate.cmd
Labels: bug

#39 Fix magento2 php-fpm 8.2 xdebug image builds
  .github/workflows/docker-image-php-fpm.yml
Labels: bug

#45 Add amqp and redis php extensions
  images/php-fpm/Dockerfile
Labels: bug, help wanted
